### ISSUE TITLE
Pass snakemake arguments to the GitHub action

### ISSUE THREAD

**Issue by arm61** [showyourwork/showyourwork-action#3]
Is it possible to pass ~~conda~~ snakemake arguments to the Github action (want to use `--restart-times 3` to get round Zenodo Sandbox problems)?

**Comment by arm61** [comment]
Sorry brain-fart, I meant `snakemake`. From `snakemake-7.7.0` there is the command line argument `--retries x` but before that it was called `--restart-times x`.

**Comment by rodluger** [comment]
I see. Locally, you can do

```
showyourwork build --restart-times 3
```

All options after `build` are forwarded to Snakemake. There's currently no way to pass these to the action, but I could implement that.

That said, are you still getting fatal errors due to caching issues? The expected behavior is for them to fail non-fatally -- it just skips trying to cache/restore a given file if there's a request error. So this approach wouldn't work, I don't think. Instead, we'd have to change the way requests are handled in the `showyourwork` repo proper. It would require a bit of rewriting of the backend, so let's talk it through before I try to implement it.

**Comment by arm61** [comment]
No longer getting issues on the local build 👍. The problem is when it runs on Github, I have like 200 rules that depend on cached things and some (where the object was definitely on Zenodo Sandbox) were failing, I think due to connection issues (hence the desire to retry/restart-times).

**Comment by arm61** [comment]
I have realised that the problem is not what I thought it was. I will close this issue and open the correct one on the `showyourwork` repo later today.
